name: email_sending

on:
  push:
    branches:
      - main
  #schedule:
   # - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your AWS region

      - name: Deploy to Lambda
        run: |
          # Add your deployment script or commands here
          # For example, use the AWS CLI or AWS SDK to deploy your Lambda function
        env:
          AWS_LAMBDA_FUNCTION_NAME: Email-sender  # Replace with your Lambda function name
      

