name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to AWS Lambda
        uses: softprops/action-aws-lambda@v4
        with:
          name: Email-sender   # Replace with your Lambda function name
          runtime: python3.11 # Replace with your desired Python runtime
          handler: lambda_function.lambda_handler  # Replace with your Lambda function handler
          zip: deploy.zip  # Replace with the path to your deployment package
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1  # Replace with your desired AWS region
